### ISSUE TITLE
Use separate locations for `app` and `app_packages`

### ISSUE THREAD

**Issue by paulproteus** [beeware/briefcase-android-gradle-template#2]
Implementation notes: Right now, the user's app and the dependencies are siblings in the filesystem tree. We need to mirror how the iOS briefcase target works in terms of separating the `app` and `app_packages`.

**Comment by freakboy3742** [comment]
Fixed in #3.

**Comment by paulproteus** [comment]
@freakboy3742 Hi! Yay! BTW... do you know what I did wrong, syntax-wise? I was hoping that merging the PR would auto-close this?

**Comment by freakboy3742** [comment]
@paulproteus So, AFAIK, the *commit* needs to start with "Fixes #N", (or Fix, Fixed, Closes, Close, Closed). I *think* that also applies to the PR title (since that becomes the first line of the merge commit message). Full reference is [here](https://guides.github.com/features/issues/#notifications).
